services:
  jupyterlab:
    container_name: jupyterlab
    image: jupyterlab:latest
    ports:
      - "8888:8888"
    develop:
      watch:
        - action: sync
          path: ../images/jupyterlab   
          target: /dockerfile
    volumes:
      - ${WORK_DIR:-/workspace} 

    working_dir: ${WORK_DIR:-/workspace} 
    networks:
      - spark-network


networks:
  spark-network:
    external: true