# Base Image 
FROM python:3.11

# Set working directory
WORKDIR /app

# Install Java and other dependencies
RUN apt-get update && \
    apt-get install -y default-jre wget && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt ${app}

# Install JupyterLab and Python libraries
RUN pip install -r /app/requirements.txt



