services:
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=user_password
    restart: always

    networks:
      - spark-network


volumes:
  minio_data:

networks:
  spark-network:
    external: true