name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas requests psycopg2-binary
      - name: Install Pylint and Custom Plugin
        run: |
          pip install pylint setuptools
          pip install .
          echo "Installed packages:"
          pip list
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files 'exploratory-ETL/dags/custom_lib/fetch_data.py')
